"""Initial Migration

Revision ID: 7db253316c0d
Revises: 
Create Date: 2023-04-20 12:39:43.537141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db253316c0d'
down_revision = None
branch_labels = None
depends_on = None


# def upgrade():
#     op.add_column('my_table', sa.Column('my_new_column', sa.String(), nullable=True))
#     op.execute("UPDATE my_table SET my_new_column='my_default_value'")
#     op.alter_column('my_table', 'my_new_column', nullable=False)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
